name: Mitt Första Workflow
on: [push]

jobs:
  # Ändrat från 'ä' till 'a' här:
  min-haftiga-jobb-del:
    runs-on: ubuntu-latest
    steps:
      - name: Steg 1
        run: echo "Hej Världen"
      - name: Steg 2
        run: pwd
      - name: Steg 3
        run: date
